version: '3'
services:
  mysql:
        image: mysql:8.0
        container_name: mysql-server-80
        command: --default-authentication-plugin=mysql_native_password
#        working_dir: /application
        volumes:
          - .:/application
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=pass
          - MYSQL_DATABASE=DB
          - MYSQL_USER=admin
          - MYSQL_PASSWORD=pass
        ports:
          - "8082:3306"
  website:
    container_name: BarDownSite
    build:
      context: ./
    ports:
      - 80:80
    depends_on:
      - mysql
    hostname: BarDown
